### ISSUE TITLE
Custom weights not working

### ISSUE THREAD

**Issue by Liiw** [iso2t/Heavy-Inventories-Issues#1]
I cannot seem to get the mod working properly. I can see the tooltip showing the "stone" amount for each item, but it is 0.1. I have tried changing the option for filegeneration to true in the config, but so far this does not seem to have any effect. 

I have tested it both in SP and dedicated server. I also have numerous other mods installed. So far, have not yet tested with this mod only. Please let me know if you have additional questions.

**Comment by Liiw** [comment]
So I tried loading the game with only HI and Supercore installed. After turning the autogenerate option on from the config I get a game crash with no crash report. I managed to get this from the latest.log:

https://pastebin.com/z1YVijCM

**Comment by Liiw** [comment]
Also, when loading the game prior to setting the config option, the game would start. I still could not set the custom weights using the commands though.

**Comment by iso2t** [comment]
i see where its erroring (a NPE). itll be fixed in the next build i push. thanks.

**Comment by Liiw** [comment]
Hello again! So I tried "Heavy+Inventories-1.12.2-3.0.1" but the weight system is not working still. I have also noticed that there is no "weights" folder with .json files created in the config folder. I tried to change values via commands, and it reports sucesses to me but no actual change takes place. All the items are still at default 0.1 stone. I have attached an image below about the command outputs. As you can see I tried changing the weight of stone to 10 and although I have other items in my inventory, the weight is still below 10, while it should be above. 

![image](https://user-images.githubusercontent.com/14122419/69001122-326f2f80-08e2-11ea-94fb-46940a2e01b1.png)

Please let me know if you need additional information.

**Comment by Liiw** [comment]
Hello! Not to sound pestering, but is there any progress on this issue?

**Comment by Liiw** [comment]
Hi would you be able to push that commit some time soon?

**Comment by DerDon1991** [comment]
I cant get the mod to generate the weights folder maybe it that is why we cant save custom weights?

**Comment by DerDon1991** [comment]
putting an empty weights folder into the heavyinventories folder fixed this issue for me since the mod will then fill in the missing data and I can change and save it.

**Comment by iso2t** [comment]
Fixed in build 3.0.2
